---
#- name: Debug vars
#  debug:
#    msg: "{{certauth.domain}}"
#  tags:
#    - root_ca

- name: Create Root CA openssl config file
  template:
    src: ca.conf.j2
    dest: "{{base_path}}/config/ca.conf"
  tags:
    - root_ca

- name: Create Root CA x509v3 extensions config file
  template:
    src: x509v3.conf.j2
    dest: "{{base_path}}/config/ca_x509v3.conf"
  tags:
    - root_ca

- name: Create Root CA CSR config file
  template:
    src: csr.conf.j2
    dest: "{{base_path}}/config/ca_csr.conf"
  tags:
    - root_ca

- name: Create Root CA private key
  shell:
    cmd: openssl ecparam -genkey -name secp384r1 | openssl ec -aes256 -passout pass:{{passphrase}} -out private/{{fqdn}}.key
    chdir: "{{base_path}}/"
    creates: "{{base_path}}/private/{{fqdn}}.key"
  tags:
    - root_ca

- name: Check Root CA private key
  command:
    cmd: openssl ec -passin pass:{{passphrase}} -in private/{{fqdn}}.key -text -check
    chdir: "{{base_path}}/"
  changed_when: False
  tags:
    - root_ca
    - verify

- name: Create Root CA certificate signing request
  command:
    argv:
      - openssl
      - req
      - -new
      - -batch
      - -config
      - config/ca_csr.conf
      - -extensions
      - v3_ext
      - -passin
      - pass:{{passphrase}}
      - -key
      - private/{{fqdn}}.key
      - -out
      - csr/{{fqdn}}.csr
    chdir: "{{base_path}}/"
    creates: "{{base_path}}/csr/{{fqdn}}.csr"
  tags:
    - root_ca

- name: Verify Root CA certificate signing request
  command:
    cmd: openssl req -text -in csr/{{fqdn}}.csr -noout -verify
    chdir: "{{base_path}}/"
  register: cmd_result
  failed_when: "'verify OK' not in cmd_result.stderr"
  changed_when: False
  tags:
    - root_ca
    - verify

- name: Sign and Create Root CA certificate from CSR
  command:
    argv:
      - openssl
      - ca
      - -batch
      - -create_serial
      - -out
      - certs/{{fqdn}}.crt
      - -days
      - "{{certauth.days|default(ca.default.days)|default('365')}}"
      - -passin
      - pass:{{passphrase}}
      - -keyfile
      - private/{{fqdn}}.key
      - -selfsign
      - -config
      - config/ca.conf
      - -infiles
      - csr/{{fqdn}}.csr
    chdir: "{{base_path}}/"
    creates: "{{base_path}}/certs/{{fqdn}}.crt"
  tags:
    - root_ca

- name: Verify Root CA certificate
  command:
    cmd: openssl x509 -noout -in certs/{{fqdn}}.crt
    chdir: "{{base_path}}/"
  changed_when: False
  tags:
    - root_ca
    - verify
