
- name: Show passphrase
  debug:
    msg: "{{passphrase}}"

- name: Show domain
  debug:
    msg: "{{domain}}"

- name: Select Authorities
  debug:
    msg: "{{item.name}}"
  with_items: "{{ca.authorities}}"
  when: item.parent is undefined
#  with_items: "{{ca.authorities|selectattr('name', 'equalto', 'services')}}"
