---
- name: Install/confirm openssl packages
  apt:
    name: "{{ package }}"
    state: present
  loop:
    - openssl
    - python-openssl
    - python3-openssl
  loop_control:
    loop_var: package
  become: yes
